services:
  frontend:
    image: ayushchoudhary6/chat-frontend:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - chatapp-network

  backend:
    image: ayushchoudhary6/chat-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/chatapp_db
      - JWT_SECRET=supersecretdev
    depends_on:
      - mongo
    networks:
      - chatapp-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chatapp-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: chatapp
  #     POSTGRES_PASSWORD: chatapp_password
  #     POSTGRES_DB: chatapp_db
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - chatapp-network

networks:
  chatapp-network:
    driver: bridge

volumes:
  mongo-data:
