#!/bin/bash

echo "# ============================================================================="
echo "# Environment Variables for GitLab CI/CD Pipeline"
echo "# ============================================================================="
echo "# Generated from .gitlab-ci.yml analysis on $(date)"
echo "# Add these variables to GitLab: Settings > CI/CD > Variables"
echo ""

# Extract all variables from GitLab CI file
echo "# ============================================================================="
echo "# DOCKER REGISTRY CONFIGURATION"
echo "# ============================================================================="
echo "CI_DOCKER_USER=your_docker_hub_username"
echo "CI_DOCKER_PASSWORD=your_docker_hub_password_or_token"
echo ""

echo "# ============================================================================="
echo "# KUBERNETES CLUSTER CONFIGURATION"
echo "# ============================================================================="
echo "KUBE_SERVER=https://your-kubernetes-cluster-api:6443"
echo "KUBE_NAMESPACE=chatapp"
echo "KUBE_CA_PEM=base64_encoded_cluster_ca_certificate"
echo "KUBE_TOKEN=your_service_account_token"
echo "# KUBE_CLIENT_CERT=base64_encoded_client_certificate  # Alternative to token"
echo "# KUBE_CLIENT_KEY=base64_encoded_client_private_key   # Alternative to token"
echo ""

echo "# ============================================================================="
echo "# APPLICATION SECRETS"
echo "# ============================================================================="
echo "MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/database"
echo "JWT_SECRET=your_super_secret_jwt_key_minimum_32_characters_long"
echo "CLOUDINARY_CLOUD_NAME=your_cloudinary_cloud_name"
echo "CLOUDINARY_API_KEY=your_cloudinary_api_key"
echo "CLOUDINARY_API_SECRET=your_cloudinary_api_secret"
echo ""

echo "# ============================================================================="
echo "# DEPLOYMENT CONFIGURATION"
echo "# ============================================================================="
echo "DOMAIN_NAME=yourdomain.com"
echo "BACKEND_REPLICAS=3"
echo "FRONTEND_REPLICAS=3"
echo ""

echo "# ============================================================================="
echo "# VARIABLE SECURITY SETTINGS FOR GITLAB"
echo "# ============================================================================="
echo "# MASKED (hidden in logs): CI_DOCKER_PASSWORD, KUBE_TOKEN, KUBE_CLIENT_KEY,"
echo "#                          MONGODB_URI, JWT_SECRET, CLOUDINARY_API_SECRET"
echo "# PROTECTED (protected branches only): KUBE_CA_PEM, KUBE_TOKEN, KUBE_CLIENT_CERT, KUBE_CLIENT_KEY"
echo "# REGULAR: All other variables"

