apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-Deployment
  namespace: chatapp
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
        - name: frontend
          image: ayushchoudhary6/chat-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: http://backend:5000
          